import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "@/app/components/navbar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/app/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <Navbar />
        <div className="px-5 mt-5">{children}</div>
      </SidebarInset>
    </SidebarProvider>
  );
}
